name: example
author: Dart Team <misc@dartlang.org>

environment:
#  sdk: '>=2.2.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.0.0
  path: ^1.5.1
  test: ^1.6.0
