# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.2.0
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.2.0]
- unit_test:
  # Run the tests -- include the default-skipped presubmit tests
  - test
  - test: --run-skipped test/ensure_build_test.dart
  - command: pub run build_runner test --delete-conflicting-outputs -- -p chrome

cache:
  directories:
  - .dart_tool/build
