name: json_serializable
version: 2.3.0-dev
author: Dart Team <misc@dartlang.org>
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  analyzer: '>=0.33.3 <0.37.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <=0.4.1+1'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  json_annotation: '>=2.1.0 <2.3.0'
  meta: ^1.1.8
  path: ^1.6.4
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.7.3
  build_verify: ^1.1.1
  #  build_web_compilers: ^1.0.0
  collection: ^1.14.12
  dart_style: ^1.2.0
  logging: ^0.11.3+2
  pub_semver: ^1.4.2
  source_gen_test: ^0.1.0+6
  test: ^1.11.0
  yaml: ^2.2.0
